version: "3"
services:
  documentation:
    build:
      context: ./
      dockerfile: Dockerfile-nodejs-development
    volumes:
      - ./:/app:rw
    ports:
      - "3002:4000"
    command: >
      sh -c '
        gitbook serve
      '

  server:
    build:
      context: ./
      dockerfile: Dockerfile-nodejs-development
    volumes:
      - ./server:/app:rw
    environment:
      - HTTP_PORT=3000
    ports:
      - "3001:3000"
    command: >
      sh -c '
        npm i && npm start
      '

  client:
    build:
      context: ./
      dockerfile: Dockerfile-nodejs-development
    volumes:
      - ./client:/app:rw
    ports:
      - "3000:3000"
    command: >
      sh -c '
        npm i && npm start
      '
