version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-development
    volumes:
      - ./server:/application:rw
    environment:
      - HTTP_PORT=3000
    ports:
      - "3000:3000"
    command: >
      sh -c '
        npm i && npm start
      '
