version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-development
    volumes:
      - ./server:/application:rw
    environment:
      - CERTIFICATE_PASSPHRASE=development!
      - HTTP_PORT=3000
      - HTTPS_PORT=3001
    ports:
      - "3000:3000"
      - "3001:3001"
    command: >
      sh -c '
        npm i && npm start
      '
