FROM node:latest

ARG NODE_ENV

ENV NODE_ENV ${NODE_ENV}
ENV HTTP_PORT 3000
ENV HTTPS_PORT 3001

COPY package.json /application/
COPY package-lock.json /application/
COPY keys/${NODE_ENV}.key /application/keys/
COPY keys/${NODE_ENV}.crt /application/keys/
COPY src /application/src/

WORKDIR /application
RUN npm i

CMD ["npm", "start"]
